version: '3.2'

services:

  db:
    image: jkatskuid/docker-postgres-uuid
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    volumes:
      - type: bind
        source: ./db_data
        target: /var/lib/postgresql/data
